name: PPV Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install chromium

      - name: Install Linux deps
        run: |
          playwright install-deps chromium

      - name: Run Test
        run: |
          python ppv_test.py
